# Generated by Django 4.2.14 on 2024-11-17 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='tipo_clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app_ml.tipoclase'),
        ),
    ]
