# Generated by Django 4.2.14 on 2024-07-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ml', '0002_dataset_best_model_path_alter_dataset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app_ml.dataset')),
            ],
            options={
                'unique_together': {('dataset', 'index')},
            },
        ),
    ]
