# Generated by Django 4.2.14 on 2024-11-18 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ml', '0002_alter_clase_tipo_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoclase',
            name='color',
            field=models.CharField(blank=True, default=None, help_text='Color en formato HEX (por ejemplo, #836752).', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='El color debe estar en formato HEX, por ejemplo: #FFFFFF', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
