# Generated by Django 4.2.14 on 2024-07-14 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ml', '0003_datasetclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationresult',
            name='predicted_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ml.datasetclass'),
        ),
    ]
